country_codes = {
    "Андорра": "countryAD",
    "Объединенные Арабские Эмираты": "countryAE",
    "Антигуа и Барбуда": "countryAG",
    "Ангилья": "countryAI",
    "Албания": "countryAL",
    "Армения": "countryAM",
    "Ангола": "countryAO",
    "Антарктида": "countryAQ",
    "Аргентина": "countryAR",
    "Американское Самоа": "countryAS",
    "Австрия": "countryAT",
    "Австралия": "countryAU",
    "Аруба": "countryAW",
    "Аландские острова": "countryAX",
    "Азербайджан": "countryAZ",
    "Босния и Герцеговина": "countryBA",
    "Барбадос": "countryBB",
    "Бангладеш": "countryBD",
    "Бельгия": "countryBE",
    "Буркина-Фасо": "countryBF",
    "Болгария": "countryBG",
    "Бахрейн": "countryBH",
    "Бурунди": "countryBI",
    "Бенин": "countryBJ",
    "Сен-Бартелеми": "countryBL",
    "Бермуды": "countryBM",
    "Бруней": "countryBN",
    "Боливия": "countryBO",
    "Бонэйр, Синт-Эстатиус и Саба": "countryBQ",
    "Бразилия": "countryBR",
    "Багамы": "countryBS",
    "Бутан": "countryBT",
    "Остров Буве": "countryBV",
    "Ботсвана": "countryBW",
    "Беларусь": "countryBY",
    "Белиз": "countryBZ",
    "Канада": "countryCA",
    "Кокосовыe острова (острова Килинг)": "countryCC",
    "Конго (ДРК)": "countryCD",
    "Центрально-Африканская Республика": "countryCF",
    "Конго (Республика)": "countryCG",
    "Швейцария": "countryCH",
    "Кот-д’Ивуар": "countryCI",
    "Острова Кука": "countryCK",
    "Чили": "countryCL",
    "Камерун": "countryCM",
    "Колумбия": "countryCO",
    "Коста-Рика": "countryCR",
    "Кабо-Верде": "countryCV",
    "Кюрасао": "countryCW",
    "Остров Рождества": "countryCX",
    "Кипр": "countryCY",
    "Чехия": "countryCZ",
    "Германия": "countryDE",
    "Джибути": "countryDJ",
    "Дания": "countryDK",
    "Доминика": "countryDM",
    "Доминиканская Республика": "countryDO",
    "Алжир": "countryDZ",
    "Эквадор": "countryEC",
    "Эстония": "countryEE",
    "Египет": "countryEG",
    "Западная Сахара": "countryEH",
    "Эритрея": "countryER",
    "Испания": "countryES",
    "Эфиопия": "countryET",
    "Финляндия": "countryFI",
    "Фиджи": "countryFJ",
    "Фолклендские острова (Мальвинские острова)": "countryFK",
    "Микронезия": "countryFM",
    "Фарерские острова": "countryFO",
    "Франция": "countryFR",
    "Габон": "countryGA",
    "Великобритания": "countryGB",
    "Гренада": "countryGD",
    "Грузия": "countryGE",
    "Французская Гвиана": "countryGF",
    "Гернси": "countryGG",
    "Гана": "countryGH",
    "Гибралтар": "countryGI",
    "Гренландия": "countryGL",
    "Гамбия": "countryGM",
    "Гвинея": "countryGN",
    "Гваделупа": "countryGP",
    "Экваториальная Гвинея": "countryGQ",
    "Греция": "countryGR",
    "Остров Южная Георгия и Южные Сандвичевы острова": "countryGS",
    "Гватемала": "countryGT",
    "Гуам": "countryGU",
    "Гвинея-Биссау": "countryGW",
    "Гайана": "countryGY",
    "Гонконг": "countryHK",
    "Остров Херд и острова Макдональд": "countryHM",
    "Гондурас": "countryHN",
    "Хорватия": "countryHR",
    "Гаити": "countryHT",
    "Венгрия": "countryHU",
    "Индонезия": "countryID",
    "Ирландия": "countryIE",
    "Израиль": "countryIL",
    "Остров Мэн": "countryIM",
    "Индия": "countryIN",
    "Британская территория в Индийском океане": "countryIO",
    "Ирак": "countryIQ",
    "Исландия": "countryIS",
    "Италия": "countryIT",
    "Джерси": "countryJE",
    "Ямайка": "countryJM",
    "Иордания": "countryJO",
    "Япония": "countryJP",
    "Кения": "countryKE",
    "Киргизия": "countryKG",
    "Камбоджа": "countryKH",
    "Кирибати": "countryKI",
    "Коморские Острова": "countryKM",
    "Сент-Китс и Невис": "countryKN",
    "Южная Корея": "countryKR",
    "Кувейт": "countryKW",
    "Каймановы острова": "countryKY",
    "Казахстан": "countryKZ",
    "Лаос": "countryLA",
    "Ливан": "countryLB",
    "Сент-Люсия": "countryLC",
    "Лихтенштейн": "countryLI",
    "Шри-Ланка": "countryLK",
    "Либерия": "countryLR",
    "Лесото": "countryLS",
    "Литва": "countryLT",
    "Люксембург": "countryLU",
    "Латвия": "countryLV",
    "Ливия": "countryLY",
    "Марокко": "countryMA",
    "Монако": "countryMC",
    "Молдова": "countryMD",
    "Черногория": "countryME",
    "Сен-Мартен": "countryMF",
    "Мадагаскар": "countryMG",
    "Маршалловы Острова": "countryMH",
    "Македония": "countryMK",
    "Мали": "countryML",
    "Мьянма (Бирма)": "countryMM",
    "Монголия": "countryMN",
    "Макао": "countryMO",
    "Северные Марианские острова": "countryMP",
    "Мартиника": "countryMQ",
    "Мавритания": "countryMR",
    "Монтсеррат": "countryMS",
    "Мальта": "countryMT",
    "Маврикий": "countryMU",
    "Мальдивы": "countryMV",
    "Малави": "countryMW",
    "Мексика": "countryMX",
    "Малайзия": "countryMY",
    "Мозамбик": "countryMZ",
    "Намибия": "countryNA",
    "Новая Каледония": "countryNC",
    "Нигер": "countryNE",
    "Остров Норфолк": "countryNF",
    "Нигерия": "countryNG",
    "Никарагуа": "countryNI",
    "Нидерланды": "countryNL",
    "Норвегия": "countryNO",
    "Непал": "countryNP",
    "Науру": "countryNR",
    "Ниуэ": "countryNU",
    "Новая Зеландия": "countryNZ",
    "Оман": "countryOM",
    "Панама": "countryPA",
    "Перу": "countryPE",
    "Французская Полинезия": "countryPF",
    "Папуа – Новая Гвинея": "countryPG",
    "Филиппины": "countryPH",
    "Пакистан": "countryPK",
    "Польша": "countryPL",
    "Сент-Пьер и Микелон": "countryPM",
    "Питкерн": "countryPN",
    "Пуэрто-Рико": "countryPR",
    "Палестина": "countryPS",
    "Португалия": "countryPT",
    "Палау": "countryPW",
    "Парагвай": "countryPY",
    "Катар": "countryQA",
    "Реюньон": "countryRE",
    "Румыния": "countryRO",
    "Сербия": "countryRS",
    "Россия": "countryRU",
    "Руанда": "countryRW",
    "Саудовская Аравия": "countrySA",
    "Соломоновы Острова": "countrySB",
    "Сейшельские Острова": "countrySC",
    "Швеция": "countrySE",
    "Сингапур": "countrySG",
    "Остров Святой Елены": "countrySH",
    "Словения": "countrySI",
    "Шпицберген и Ян-Майен": "countrySJ",
    "Словакия": "countrySK",
    "Сьерра-Леоне": "countrySL",
    "Сан-Марино": "countrySM",
    "Сенегал": "countrySN",
    "Сомали": "countrySO",
    "Суринам": "countrySR",
    "Южный Судан": "countrySS",
    "Сан-Томе и Принсипи": "countryST",
    "Сальвадор": "countrySV",
    "Синт-Мартен": "countrySX",
    "Свазиленд": "countrySZ",
    "Тристан-да-Кунья": "countryTA",
    "Тёркс и Кайкос": "countryTC",
    "Чад": "countryTD",
    "Французские Южные территории": "countryTF",
    "Того": "countryTG",
    "Таиланд": "countryTH",
    "Таджикистан": "countryTJ",
    "Токелау": "countryTK",
    "Восточный Тимор": "countryTL",
    "Туркменистан": "countryTM",
    "Тунис": "countryTN",
    "Тонга": "countryTO",
    "Турция": "countryTR",
    "Тринидад и Тобаго": "countryTT",
    "Тувалу": "countryTV",
    "Тайвань": "countryTW",
    "Танзания": "countryTZ",
    "Украина": "countryUA",
    "Уганда": "countryUG",
    "Малые Тихоокеанские Отдаленные острова США": "countryUM",
    "США": "countryUS",
    "Уругвай": "countryUY",
    "Узбекистан": "countryUZ",
    "Ватикан": "countryVA",
    "Сент-Винсент и Гренадины": "countryVC",
    "Венесуэла": "countryVE",
    "Британские Виргинские острова": "countryVG",
    "Американские Виргинские острова": "countryVI",
    "Вьетнам": "countryVN",
    "Вануату": "countryVU",
    "Уоллис и Футуна": "countryWF",
    "Самоа": "countryWS",
    "Косово": "countryXK",
    "Йемен": "countryYE",
    "Майотта": "countryYT",
    "ЮАР": "countryZA",
    "Замбия": "countryZM",
    "Зимбабве": "countryZW"
}